/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using EdGraph.Platform.Client.Api;
using EdGraph.Platform.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace EdGraph.Platform.Client.Test.Api
{
    /// <summary>
    ///  Class for testing EdFiSyncApi
    /// </summary>
    public sealed class EdFiSyncApiTests : ApiTestsBase
    {
        private readonly IEdFiSyncApi _instance;

        public EdFiSyncApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IEdFiSyncApi>();
        }

        /// <summary>
        /// Test CreateEdFiSync
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateEdFiSyncAsyncTest()
        {
            string tenantId = default!;
            Client.Option<EdGraphHttpAggregatorsTenantApiServicesEdFiRosterSyncCreateEdFiRosterSyncJobRequestDto> edGraphHttpAggregatorsTenantApiServicesEdFiRosterSyncCreateEdFiRosterSyncJobRequestDto = default!;
            var response = await _instance.CreateEdFiSyncAsync(tenantId, edGraphHttpAggregatorsTenantApiServicesEdFiRosterSyncCreateEdFiRosterSyncJobRequestDto);
            var model = response.Unauthorized();
            Assert.IsType<EdGraphHttpAggregatorsTenantApiServicesEdFiRosterSyncJobCreatedResult>(model);
        }

        /// <summary>
        /// Test ExecuteEdFiSyncJob
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ExecuteEdFiSyncJobAsyncTest()
        {
            Guid tenantId = default!;
            var response = await _instance.ExecuteEdFiSyncJobAsync(tenantId);
            var model = response.Unauthorized();
            Assert.IsType<DataSyncApiJobV1JobExecutionRequestedResponse>(model);
        }

        /// <summary>
        /// Test GetEdFiSyncData
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetEdFiSyncDataAsyncTest()
        {
            Guid tenantId = default!;
            var response = await _instance.GetEdFiSyncDataAsync(tenantId);
            var model = response.Unauthorized();
            Assert.IsType<DataSyncApiEdFiRosterSyncV1EdFiRosterSyncJobProfile>(model);
        }

        /// <summary>
        /// Test UpdateEdFiSync
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateEdFiSyncAsyncTest()
        {
            Guid tenantId = default!;
            Client.Option<Object?> body = default!;
            var response = await _instance.UpdateEdFiSyncAsync(tenantId, body);
            var model = response.Unauthorized();
            Assert.IsType<MicrosoftAspNetCoreMvcNoContentResult>(model);
        }
    }
}
