// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders
    /// </summary>
    public partial class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders" /> class.
        /// </summary>
        /// <param name="identityProviderId">identityProviderId</param>
        /// <param name="identityProviderStatus">identityProviderStatus</param>
        /// <param name="enableMfa">enableMfa</param>
        /// <param name="enforceMfa">enforceMfa</param>
        [JsonConstructor]
        public EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders(Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderId?> identityProviderId = default, Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderStatus?> identityProviderStatus = default, Option<bool?> enableMfa = default, Option<string?> enforceMfa = default)
        {
            IdentityProviderIdOption = identityProviderId;
            IdentityProviderStatusOption = identityProviderStatus;
            EnableMfaOption = enableMfa;
            EnforceMfaOption = enforceMfa;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IdentityProviderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderId?> IdentityProviderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets IdentityProviderId
        /// </summary>
        [JsonPropertyName("identityProviderId")]
        public EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderId? IdentityProviderId { get { return this.IdentityProviderIdOption; } set { this.IdentityProviderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IdentityProviderStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderStatus?> IdentityProviderStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets IdentityProviderStatus
        /// </summary>
        [JsonPropertyName("identityProviderStatus")]
        public EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderStatus? IdentityProviderStatus { get { return this.IdentityProviderStatusOption; } set { this.IdentityProviderStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableMfa
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableMfaOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableMfa
        /// </summary>
        [JsonPropertyName("enableMfa")]
        public bool? EnableMfa { get { return this.EnableMfaOption; } set { this.EnableMfaOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnforceMfa
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EnforceMfaOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnforceMfa
        /// </summary>
        [JsonPropertyName("enforceMfa")]
        public string? EnforceMfa { get { return this.EnforceMfaOption; } set { this.EnforceMfaOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders {\n");
            sb.Append("  IdentityProviderId: ").Append(IdentityProviderId).Append("\n");
            sb.Append("  IdentityProviderStatus: ").Append(IdentityProviderStatus).Append("\n");
            sb.Append("  EnableMfa: ").Append(EnableMfa).Append("\n");
            sb.Append("  EnforceMfa: ").Append(EnforceMfa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders" />
    /// </summary>
    public class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProvidersJsonConverter : JsonConverter<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderId?> identityProviderId = default;
            Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderStatus?> identityProviderStatus = default;
            Option<bool?> enableMfa = default;
            Option<string?> enforceMfa = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "identityProviderId":
                            string? identityProviderIdRawValue = utf8JsonReader.GetString();
                            if (identityProviderIdRawValue != null)
                                identityProviderId = new Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderId?>(EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderIdValueConverter.FromStringOrDefault(identityProviderIdRawValue));
                            break;
                        case "identityProviderStatus":
                            string? identityProviderStatusRawValue = utf8JsonReader.GetString();
                            if (identityProviderStatusRawValue != null)
                                identityProviderStatus = new Option<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderStatus?>(EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderStatusValueConverter.FromStringOrDefault(identityProviderStatusRawValue));
                            break;
                        case "enableMfa":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enableMfa = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "enforceMfa":
                            enforceMfa = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (identityProviderId.IsSet && identityProviderId.Value == null)
                throw new ArgumentNullException(nameof(identityProviderId), "Property is not nullable for class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.");

            if (identityProviderStatus.IsSet && identityProviderStatus.Value == null)
                throw new ArgumentNullException(nameof(identityProviderStatus), "Property is not nullable for class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.");

            if (enableMfa.IsSet && enableMfa.Value == null)
                throw new ArgumentNullException(nameof(enableMfa), "Property is not nullable for class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.");

            return new EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders(identityProviderId, identityProviderStatus, enableMfa, enforceMfa);
        }

        /// <summary>
        /// Serializes a <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.IdentityProviderIdOption.IsSet)
            {
                var identityProviderIdRawValue = EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderIdValueConverter.ToJsonValue(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.IdentityProviderId!.Value);
                writer.WriteString("identityProviderId", identityProviderIdRawValue);
            }
            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.IdentityProviderStatusOption.IsSet)
            {
                var identityProviderStatusRawValue = EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviderStatusValueConverter.ToJsonValue(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.IdentityProviderStatus!.Value);
                writer.WriteString("identityProviderStatus", identityProviderStatusRawValue);
            }
            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.EnableMfaOption.IsSet)
                writer.WriteBoolean("enableMfa", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.EnableMfaOption.Value!.Value);

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.EnforceMfaOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.EnforceMfaOption.Value != null)
                    writer.WriteString("enforceMfa", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsTenantsTenantIdentityProviders.EnforceMfa);
                else
                    writer.WriteNull("enforceMfa");
        }
    }
}
