// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// ValidationsApiDbEnvironmentsV1TestConnectionRequest
    /// </summary>
    public partial class ValidationsApiDbEnvironmentsV1TestConnectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationsApiDbEnvironmentsV1TestConnectionRequest" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="connectionType">connectionType</param>
        /// <param name="sqlServerConnection">sqlServerConnection</param>
        /// <param name="azureSynapseSqlServerlessConnection">azureSynapseSqlServerlessConnection</param>
        [JsonConstructor]
        public ValidationsApiDbEnvironmentsV1TestConnectionRequest(Option<string?> id = default, Option<string?> connectionType = default, Option<ValidationsApiDbEnvironmentsV1SqlServerConnection?> sqlServerConnection = default, Option<ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection?> azureSynapseSqlServerlessConnection = default)
        {
            IdOption = id;
            ConnectionTypeOption = connectionType;
            SqlServerConnectionOption = sqlServerConnection;
            AzureSynapseSqlServerlessConnectionOption = azureSynapseSqlServerlessConnection;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConnectionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConnectionTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConnectionType
        /// </summary>
        [JsonPropertyName("connectionType")]
        public string? ConnectionType { get { return this.ConnectionTypeOption; } set { this.ConnectionTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of SqlServerConnection
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ValidationsApiDbEnvironmentsV1SqlServerConnection?> SqlServerConnectionOption { get; private set; }

        /// <summary>
        /// Gets or Sets SqlServerConnection
        /// </summary>
        [JsonPropertyName("sqlServerConnection")]
        public ValidationsApiDbEnvironmentsV1SqlServerConnection? SqlServerConnection { get { return this.SqlServerConnectionOption; } set { this.SqlServerConnectionOption = new(value); } }

        /// <summary>
        /// Used to track the state of AzureSynapseSqlServerlessConnection
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection?> AzureSynapseSqlServerlessConnectionOption { get; private set; }

        /// <summary>
        /// Gets or Sets AzureSynapseSqlServerlessConnection
        /// </summary>
        [JsonPropertyName("azureSynapseSqlServerlessConnection")]
        public ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection? AzureSynapseSqlServerlessConnection { get { return this.AzureSynapseSqlServerlessConnectionOption; } set { this.AzureSynapseSqlServerlessConnectionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationsApiDbEnvironmentsV1TestConnectionRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ConnectionType: ").Append(ConnectionType).Append("\n");
            sb.Append("  SqlServerConnection: ").Append(SqlServerConnection).Append("\n");
            sb.Append("  AzureSynapseSqlServerlessConnection: ").Append(AzureSynapseSqlServerlessConnection).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ValidationsApiDbEnvironmentsV1TestConnectionRequest" />
    /// </summary>
    public class ValidationsApiDbEnvironmentsV1TestConnectionRequestJsonConverter : JsonConverter<ValidationsApiDbEnvironmentsV1TestConnectionRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ValidationsApiDbEnvironmentsV1TestConnectionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ValidationsApiDbEnvironmentsV1TestConnectionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> connectionType = default;
            Option<ValidationsApiDbEnvironmentsV1SqlServerConnection?> sqlServerConnection = default;
            Option<ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection?> azureSynapseSqlServerlessConnection = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "connectionType":
                            connectionType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sqlServerConnection":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                sqlServerConnection = new Option<ValidationsApiDbEnvironmentsV1SqlServerConnection?>(JsonSerializer.Deserialize<ValidationsApiDbEnvironmentsV1SqlServerConnection>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "azureSynapseSqlServerlessConnection":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                azureSynapseSqlServerlessConnection = new Option<ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection?>(JsonSerializer.Deserialize<ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (sqlServerConnection.IsSet && sqlServerConnection.Value == null)
                throw new ArgumentNullException(nameof(sqlServerConnection), "Property is not nullable for class ValidationsApiDbEnvironmentsV1TestConnectionRequest.");

            if (azureSynapseSqlServerlessConnection.IsSet && azureSynapseSqlServerlessConnection.Value == null)
                throw new ArgumentNullException(nameof(azureSynapseSqlServerlessConnection), "Property is not nullable for class ValidationsApiDbEnvironmentsV1TestConnectionRequest.");

            return new ValidationsApiDbEnvironmentsV1TestConnectionRequest(id, connectionType, sqlServerConnection, azureSynapseSqlServerlessConnection);
        }

        /// <summary>
        /// Serializes a <see cref="ValidationsApiDbEnvironmentsV1TestConnectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationsApiDbEnvironmentsV1TestConnectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ValidationsApiDbEnvironmentsV1TestConnectionRequest validationsApiDbEnvironmentsV1TestConnectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, validationsApiDbEnvironmentsV1TestConnectionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ValidationsApiDbEnvironmentsV1TestConnectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationsApiDbEnvironmentsV1TestConnectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ValidationsApiDbEnvironmentsV1TestConnectionRequest validationsApiDbEnvironmentsV1TestConnectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (validationsApiDbEnvironmentsV1TestConnectionRequest.SqlServerConnectionOption.IsSet && validationsApiDbEnvironmentsV1TestConnectionRequest.SqlServerConnection == null)
                throw new ArgumentNullException(nameof(validationsApiDbEnvironmentsV1TestConnectionRequest.SqlServerConnection), "Property is required for class ValidationsApiDbEnvironmentsV1TestConnectionRequest.");

            if (validationsApiDbEnvironmentsV1TestConnectionRequest.AzureSynapseSqlServerlessConnectionOption.IsSet && validationsApiDbEnvironmentsV1TestConnectionRequest.AzureSynapseSqlServerlessConnection == null)
                throw new ArgumentNullException(nameof(validationsApiDbEnvironmentsV1TestConnectionRequest.AzureSynapseSqlServerlessConnection), "Property is required for class ValidationsApiDbEnvironmentsV1TestConnectionRequest.");

            if (validationsApiDbEnvironmentsV1TestConnectionRequest.IdOption.IsSet)
                if (validationsApiDbEnvironmentsV1TestConnectionRequest.IdOption.Value != null)
                    writer.WriteString("id", validationsApiDbEnvironmentsV1TestConnectionRequest.Id);
                else
                    writer.WriteNull("id");

            if (validationsApiDbEnvironmentsV1TestConnectionRequest.ConnectionTypeOption.IsSet)
                if (validationsApiDbEnvironmentsV1TestConnectionRequest.ConnectionTypeOption.Value != null)
                    writer.WriteString("connectionType", validationsApiDbEnvironmentsV1TestConnectionRequest.ConnectionType);
                else
                    writer.WriteNull("connectionType");

            if (validationsApiDbEnvironmentsV1TestConnectionRequest.SqlServerConnectionOption.IsSet)
            {
                writer.WritePropertyName("sqlServerConnection");
                JsonSerializer.Serialize(writer, validationsApiDbEnvironmentsV1TestConnectionRequest.SqlServerConnection, jsonSerializerOptions);
            }
            if (validationsApiDbEnvironmentsV1TestConnectionRequest.AzureSynapseSqlServerlessConnectionOption.IsSet)
            {
                writer.WritePropertyName("azureSynapseSqlServerlessConnection");
                JsonSerializer.Serialize(writer, validationsApiDbEnvironmentsV1TestConnectionRequest.AzureSynapseSqlServerlessConnection, jsonSerializerOptions);
            }
        }
    }
}
