// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest
    /// </summary>
    public partial class EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId</param>
        /// <param name="instanceId">instanceId</param>
        /// <param name="entries">entries</param>
        [JsonConstructor]
        public EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest(Option<string?> tenantId = default, Option<string?> instanceId = default, Option<List<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry>?> entries = default)
        {
            TenantIdOption = tenantId;
            InstanceIdOption = instanceId;
            EntriesOption = entries;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string? TenantId { get { return this.TenantIdOption.Value; } set { this.TenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstanceId
        /// </summary>
        [JsonPropertyName("instanceId")]
        public string? InstanceId { get { return this.InstanceIdOption.Value; } set { this.InstanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Entries
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry>?> EntriesOption { get; }

        /// <summary>
        /// Gets or Sets Entries
        /// </summary>
        [JsonPropertyName("entries")]
        public List<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry>? Entries { get { return this.EntriesOption.Value; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  Entries: ").Append(Entries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest" />
    /// </summary>
    public class EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestJsonConverter : JsonConverter<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> tenantId = default;
            Option<string?> instanceId = default;
            Option<List<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry>?> entries = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "instanceId":
                            instanceId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "entries":
                            entries = new Option<List<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry>?>(JsonSerializer.Deserialize<List<EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequestEntry>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest(tenantId, instanceId, entries);
        }

        /// <summary>
        /// Serializes a <see cref="EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.TenantIdOption.IsSet)
                if (edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.TenantIdOption.Value != null)
                    writer.WriteString("tenantId", edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.TenantId);
                else
                    writer.WriteNull("tenantId");

            if (edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.InstanceIdOption.IsSet)
                if (edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.InstanceIdOption.Value != null)
                    writer.WriteString("instanceId", edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.InstanceId);
                else
                    writer.WriteNull("instanceId");

            if (edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.EntriesOption.IsSet)
                if (edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.EntriesOption.Value != null)
                {
                    writer.WritePropertyName("entries");
                    JsonSerializer.Serialize(writer, edfiAdminApiEdfiAdminV1AddSchoolYearRangeRequest.Entries, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("entries");
        }
    }
}
