// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// EdFiAdminApiApplicationAccessV1ApplicationAccessResponse
    /// </summary>
    public partial class EdFiAdminApiApplicationAccessV1ApplicationAccessResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiAdminApiApplicationAccessV1ApplicationAccessResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="applicationId">applicationId</param>
        /// <param name="apiClientId">apiClientId</param>
        /// <param name="users">users</param>
        [JsonConstructor]
        public EdFiAdminApiApplicationAccessV1ApplicationAccessResponse(Option<string?> id = default, Option<string?> tenantId = default, Option<int?> applicationId = default, Option<int?> apiClientId = default, Option<List<EdFiAdminApiApplicationAccessV1ApplicationUserAccessResponse>?> users = default)
        {
            IdOption = id;
            TenantIdOption = tenantId;
            ApplicationIdOption = applicationId;
            ApiClientIdOption = apiClientId;
            UsersOption = users;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string? TenantId { get { return this.TenantIdOption.Value; } set { this.TenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApplicationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ApplicationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplicationId
        /// </summary>
        [JsonPropertyName("applicationId")]
        public int? ApplicationId { get { return this.ApplicationIdOption.Value; } set { this.ApplicationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApiClientId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ApiClientIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiClientId
        /// </summary>
        [JsonPropertyName("apiClientId")]
        public int? ApiClientId { get { return this.ApiClientIdOption.Value; } set { this.ApiClientIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Users
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EdFiAdminApiApplicationAccessV1ApplicationUserAccessResponse>?> UsersOption { get; }

        /// <summary>
        /// Gets or Sets Users
        /// </summary>
        [JsonPropertyName("users")]
        public List<EdFiAdminApiApplicationAccessV1ApplicationUserAccessResponse>? Users { get { return this.UsersOption.Value; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiAdminApiApplicationAccessV1ApplicationAccessResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  ApplicationId: ").Append(ApplicationId).Append("\n");
            sb.Append("  ApiClientId: ").Append(ApiClientId).Append("\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiAdminApiApplicationAccessV1ApplicationAccessResponse" />
    /// </summary>
    public class EdFiAdminApiApplicationAccessV1ApplicationAccessResponseJsonConverter : JsonConverter<EdFiAdminApiApplicationAccessV1ApplicationAccessResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdFiAdminApiApplicationAccessV1ApplicationAccessResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiAdminApiApplicationAccessV1ApplicationAccessResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> tenantId = default;
            Option<int?> applicationId = default;
            Option<int?> apiClientId = default;
            Option<List<EdFiAdminApiApplicationAccessV1ApplicationUserAccessResponse>?> users = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "applicationId":
                            applicationId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "apiClientId":
                            apiClientId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "users":
                            users = new Option<List<EdFiAdminApiApplicationAccessV1ApplicationUserAccessResponse>?>(JsonSerializer.Deserialize<List<EdFiAdminApiApplicationAccessV1ApplicationUserAccessResponse>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (applicationId.IsSet && applicationId.Value == null)
                throw new ArgumentNullException(nameof(applicationId), "Property is not nullable for class EdFiAdminApiApplicationAccessV1ApplicationAccessResponse.");

            if (apiClientId.IsSet && apiClientId.Value == null)
                throw new ArgumentNullException(nameof(apiClientId), "Property is not nullable for class EdFiAdminApiApplicationAccessV1ApplicationAccessResponse.");

            return new EdFiAdminApiApplicationAccessV1ApplicationAccessResponse(id, tenantId, applicationId, apiClientId, users);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiAdminApiApplicationAccessV1ApplicationAccessResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiAdminApiApplicationAccessV1ApplicationAccessResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiAdminApiApplicationAccessV1ApplicationAccessResponse edFiAdminApiApplicationAccessV1ApplicationAccessResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiAdminApiApplicationAccessV1ApplicationAccessResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiAdminApiApplicationAccessV1ApplicationAccessResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiAdminApiApplicationAccessV1ApplicationAccessResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiAdminApiApplicationAccessV1ApplicationAccessResponse edFiAdminApiApplicationAccessV1ApplicationAccessResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.IdOption.IsSet)
                if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.IdOption.Value != null)
                    writer.WriteString("id", edFiAdminApiApplicationAccessV1ApplicationAccessResponse.Id);
                else
                    writer.WriteNull("id");

            if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.TenantIdOption.IsSet)
                if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.TenantIdOption.Value != null)
                    writer.WriteString("tenantId", edFiAdminApiApplicationAccessV1ApplicationAccessResponse.TenantId);
                else
                    writer.WriteNull("tenantId");

            if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.ApplicationIdOption.IsSet)
                writer.WriteNumber("applicationId", edFiAdminApiApplicationAccessV1ApplicationAccessResponse.ApplicationIdOption.Value!.Value);

            if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.ApiClientIdOption.IsSet)
                writer.WriteNumber("apiClientId", edFiAdminApiApplicationAccessV1ApplicationAccessResponse.ApiClientIdOption.Value!.Value);

            if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.UsersOption.IsSet)
                if (edFiAdminApiApplicationAccessV1ApplicationAccessResponse.UsersOption.Value != null)
                {
                    writer.WritePropertyName("users");
                    JsonSerializer.Serialize(writer, edFiAdminApiApplicationAccessV1ApplicationAccessResponse.Users, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("users");
        }
    }
}
