// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse
    /// </summary>
    public partial class EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId</param>
        /// <param name="instanceId">instanceId</param>
        /// <param name="instanceApplicationId">instanceApplicationId</param>
        /// <param name="name">name</param>
        /// <param name="apiClients">apiClients</param>
        /// <param name="createdBy">createdBy</param>
        /// <param name="createdDateTime">createdDateTime</param>
        /// <param name="lastModifiedBy">lastModifiedBy</param>
        /// <param name="lastModifiedDateTime">lastModifiedDateTime</param>
        [JsonConstructor]
        public EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse(Option<string?> tenantId = default, Option<string?> instanceId = default, Option<string?> instanceApplicationId = default, Option<string?> name = default, Option<List<EdfiAdminApiEdfiAdminV1InstanceApiClientProfileResponse>?> apiClients = default, Option<string?> createdBy = default, Option<string?> createdDateTime = default, Option<string?> lastModifiedBy = default, Option<string?> lastModifiedDateTime = default)
        {
            TenantIdOption = tenantId;
            InstanceIdOption = instanceId;
            InstanceApplicationIdOption = instanceApplicationId;
            NameOption = name;
            ApiClientsOption = apiClients;
            CreatedByOption = createdBy;
            CreatedDateTimeOption = createdDateTime;
            LastModifiedByOption = lastModifiedBy;
            LastModifiedDateTimeOption = lastModifiedDateTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string? TenantId { get { return this.TenantIdOption.Value; } set { this.TenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstanceId
        /// </summary>
        [JsonPropertyName("instanceId")]
        public string? InstanceId { get { return this.InstanceIdOption.Value; } set { this.InstanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstanceApplicationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceApplicationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstanceApplicationId
        /// </summary>
        [JsonPropertyName("instanceApplicationId")]
        public string? InstanceApplicationId { get { return this.InstanceApplicationIdOption.Value; } set { this.InstanceApplicationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApiClients
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EdfiAdminApiEdfiAdminV1InstanceApiClientProfileResponse>?> ApiClientsOption { get; }

        /// <summary>
        /// Gets or Sets ApiClients
        /// </summary>
        [JsonPropertyName("apiClients")]
        public List<EdfiAdminApiEdfiAdminV1InstanceApiClientProfileResponse>? ApiClients { get { return this.ApiClientsOption.Value; } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [JsonPropertyName("createdBy")]
        public string? CreatedBy { get { return this.CreatedByOption.Value; } set { this.CreatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedDateTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedDateTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedDateTime
        /// </summary>
        [JsonPropertyName("createdDateTime")]
        public string? CreatedDateTime { get { return this.CreatedDateTimeOption.Value; } set { this.CreatedDateTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastModifiedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastModifiedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastModifiedBy
        /// </summary>
        [JsonPropertyName("lastModifiedBy")]
        public string? LastModifiedBy { get { return this.LastModifiedByOption.Value; } set { this.LastModifiedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastModifiedDateTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastModifiedDateTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastModifiedDateTime
        /// </summary>
        [JsonPropertyName("lastModifiedDateTime")]
        public string? LastModifiedDateTime { get { return this.LastModifiedDateTimeOption.Value; } set { this.LastModifiedDateTimeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  InstanceApplicationId: ").Append(InstanceApplicationId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ApiClients: ").Append(ApiClients).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedDateTime: ").Append(CreatedDateTime).Append("\n");
            sb.Append("  LastModifiedBy: ").Append(LastModifiedBy).Append("\n");
            sb.Append("  LastModifiedDateTime: ").Append(LastModifiedDateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse" />
    /// </summary>
    public class EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponseJsonConverter : JsonConverter<EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> tenantId = default;
            Option<string?> instanceId = default;
            Option<string?> instanceApplicationId = default;
            Option<string?> name = default;
            Option<List<EdfiAdminApiEdfiAdminV1InstanceApiClientProfileResponse>?> apiClients = default;
            Option<string?> createdBy = default;
            Option<string?> createdDateTime = default;
            Option<string?> lastModifiedBy = default;
            Option<string?> lastModifiedDateTime = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "instanceId":
                            instanceId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "instanceApplicationId":
                            instanceApplicationId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "apiClients":
                            apiClients = new Option<List<EdfiAdminApiEdfiAdminV1InstanceApiClientProfileResponse>?>(JsonSerializer.Deserialize<List<EdfiAdminApiEdfiAdminV1InstanceApiClientProfileResponse>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "createdBy":
                            createdBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "createdDateTime":
                            createdDateTime = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastModifiedBy":
                            lastModifiedBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastModifiedDateTime":
                            lastModifiedDateTime = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse(tenantId, instanceId, instanceApplicationId, name, apiClients, createdBy, createdDateTime, lastModifiedBy, lastModifiedDateTime);
        }

        /// <summary>
        /// Serializes a <see cref="EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.TenantIdOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.TenantIdOption.Value != null)
                    writer.WriteString("tenantId", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.TenantId);
                else
                    writer.WriteNull("tenantId");

            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.InstanceIdOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.InstanceIdOption.Value != null)
                    writer.WriteString("instanceId", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.InstanceId);
                else
                    writer.WriteNull("instanceId");

            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.InstanceApplicationIdOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.InstanceApplicationIdOption.Value != null)
                    writer.WriteString("instanceApplicationId", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.InstanceApplicationId);
                else
                    writer.WriteNull("instanceApplicationId");

            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.NameOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.NameOption.Value != null)
                    writer.WriteString("name", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.Name);
                else
                    writer.WriteNull("name");

            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.ApiClientsOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.ApiClientsOption.Value != null)
                {
                    writer.WritePropertyName("apiClients");
                    JsonSerializer.Serialize(writer, edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.ApiClients, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("apiClients");
            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.CreatedByOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.CreatedByOption.Value != null)
                    writer.WriteString("createdBy", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.CreatedBy);
                else
                    writer.WriteNull("createdBy");

            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.CreatedDateTimeOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.CreatedDateTimeOption.Value != null)
                    writer.WriteString("createdDateTime", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.CreatedDateTime);
                else
                    writer.WriteNull("createdDateTime");

            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.LastModifiedByOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.LastModifiedByOption.Value != null)
                    writer.WriteString("lastModifiedBy", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.LastModifiedBy);
                else
                    writer.WriteNull("lastModifiedBy");

            if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.LastModifiedDateTimeOption.IsSet)
                if (edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.LastModifiedDateTimeOption.Value != null)
                    writer.WriteString("lastModifiedDateTime", edfiAdminApiEdfiAdminV1InstanceApplicationProfileResponse.LastModifiedDateTime);
                else
                    writer.WriteNull("lastModifiedDateTime");
        }
    }
}
