// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// EdGraphServicesStateReportingV1EnvironmentListResponse
    /// </summary>
    public partial class EdGraphServicesStateReportingV1EnvironmentListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdGraphServicesStateReportingV1EnvironmentListResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="createdBy">createdBy</param>
        /// <param name="createdDateTime">createdDateTime</param>
        /// <param name="lastModifiedBy">lastModifiedBy</param>
        /// <param name="lastModifiedDateTime">lastModifiedDateTime</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="year">year</param>
        /// <param name="dbEnvironmentId">dbEnvironmentId</param>
        /// <param name="edFiInstanceId">edFiInstanceId</param>
        /// <param name="mode">mode</param>
        [JsonConstructor]
        public EdGraphServicesStateReportingV1EnvironmentListResponse(Option<string?> id = default, Option<string?> createdBy = default, Option<string?> createdDateTime = default, Option<string?> lastModifiedBy = default, Option<string?> lastModifiedDateTime = default, Option<string?> tenantId = default, Option<int?> year = default, Option<string?> dbEnvironmentId = default, Option<string?> edFiInstanceId = default, Option<string?> mode = default)
        {
            IdOption = id;
            CreatedByOption = createdBy;
            CreatedDateTimeOption = createdDateTime;
            LastModifiedByOption = lastModifiedBy;
            LastModifiedDateTimeOption = lastModifiedDateTime;
            TenantIdOption = tenantId;
            YearOption = year;
            DbEnvironmentIdOption = dbEnvironmentId;
            EdFiInstanceIdOption = edFiInstanceId;
            ModeOption = mode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [JsonPropertyName("createdBy")]
        public string? CreatedBy { get { return this.CreatedByOption; } set { this.CreatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedDateTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedDateTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedDateTime
        /// </summary>
        [JsonPropertyName("createdDateTime")]
        public string? CreatedDateTime { get { return this.CreatedDateTimeOption; } set { this.CreatedDateTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastModifiedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastModifiedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastModifiedBy
        /// </summary>
        [JsonPropertyName("lastModifiedBy")]
        public string? LastModifiedBy { get { return this.LastModifiedByOption; } set { this.LastModifiedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastModifiedDateTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastModifiedDateTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastModifiedDateTime
        /// </summary>
        [JsonPropertyName("lastModifiedDateTime")]
        public string? LastModifiedDateTime { get { return this.LastModifiedDateTimeOption; } set { this.LastModifiedDateTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string? TenantId { get { return this.TenantIdOption; } set { this.TenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Year
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> YearOption { get; private set; }

        /// <summary>
        /// Gets or Sets Year
        /// </summary>
        [JsonPropertyName("year")]
        public int? Year { get { return this.YearOption; } set { this.YearOption = new(value); } }

        /// <summary>
        /// Used to track the state of DbEnvironmentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DbEnvironmentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DbEnvironmentId
        /// </summary>
        [JsonPropertyName("dbEnvironmentId")]
        public string? DbEnvironmentId { get { return this.DbEnvironmentIdOption; } set { this.DbEnvironmentIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of EdFiInstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EdFiInstanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EdFiInstanceId
        /// </summary>
        [JsonPropertyName("edFiInstanceId")]
        public string? EdFiInstanceId { get { return this.EdFiInstanceIdOption; } set { this.EdFiInstanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Mode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [JsonPropertyName("mode")]
        public string? Mode { get { return this.ModeOption; } set { this.ModeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdGraphServicesStateReportingV1EnvironmentListResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedDateTime: ").Append(CreatedDateTime).Append("\n");
            sb.Append("  LastModifiedBy: ").Append(LastModifiedBy).Append("\n");
            sb.Append("  LastModifiedDateTime: ").Append(LastModifiedDateTime).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  DbEnvironmentId: ").Append(DbEnvironmentId).Append("\n");
            sb.Append("  EdFiInstanceId: ").Append(EdFiInstanceId).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdGraphServicesStateReportingV1EnvironmentListResponse" />
    /// </summary>
    public class EdGraphServicesStateReportingV1EnvironmentListResponseJsonConverter : JsonConverter<EdGraphServicesStateReportingV1EnvironmentListResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdGraphServicesStateReportingV1EnvironmentListResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdGraphServicesStateReportingV1EnvironmentListResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> createdBy = default;
            Option<string?> createdDateTime = default;
            Option<string?> lastModifiedBy = default;
            Option<string?> lastModifiedDateTime = default;
            Option<string?> tenantId = default;
            Option<int?> year = default;
            Option<string?> dbEnvironmentId = default;
            Option<string?> edFiInstanceId = default;
            Option<string?> mode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "createdBy":
                            createdBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "createdDateTime":
                            createdDateTime = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastModifiedBy":
                            lastModifiedBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastModifiedDateTime":
                            lastModifiedDateTime = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "year":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                year = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "dbEnvironmentId":
                            dbEnvironmentId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "edFiInstanceId":
                            edFiInstanceId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "mode":
                            mode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (year.IsSet && year.Value == null)
                throw new ArgumentNullException(nameof(year), "Property is not nullable for class EdGraphServicesStateReportingV1EnvironmentListResponse.");

            return new EdGraphServicesStateReportingV1EnvironmentListResponse(id, createdBy, createdDateTime, lastModifiedBy, lastModifiedDateTime, tenantId, year, dbEnvironmentId, edFiInstanceId, mode);
        }

        /// <summary>
        /// Serializes a <see cref="EdGraphServicesStateReportingV1EnvironmentListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphServicesStateReportingV1EnvironmentListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdGraphServicesStateReportingV1EnvironmentListResponse edGraphServicesStateReportingV1EnvironmentListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edGraphServicesStateReportingV1EnvironmentListResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdGraphServicesStateReportingV1EnvironmentListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphServicesStateReportingV1EnvironmentListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdGraphServicesStateReportingV1EnvironmentListResponse edGraphServicesStateReportingV1EnvironmentListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edGraphServicesStateReportingV1EnvironmentListResponse.IdOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.IdOption.Value != null)
                    writer.WriteString("id", edGraphServicesStateReportingV1EnvironmentListResponse.Id);
                else
                    writer.WriteNull("id");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.CreatedByOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.CreatedByOption.Value != null)
                    writer.WriteString("createdBy", edGraphServicesStateReportingV1EnvironmentListResponse.CreatedBy);
                else
                    writer.WriteNull("createdBy");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.CreatedDateTimeOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.CreatedDateTimeOption.Value != null)
                    writer.WriteString("createdDateTime", edGraphServicesStateReportingV1EnvironmentListResponse.CreatedDateTime);
                else
                    writer.WriteNull("createdDateTime");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.LastModifiedByOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.LastModifiedByOption.Value != null)
                    writer.WriteString("lastModifiedBy", edGraphServicesStateReportingV1EnvironmentListResponse.LastModifiedBy);
                else
                    writer.WriteNull("lastModifiedBy");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.LastModifiedDateTimeOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.LastModifiedDateTimeOption.Value != null)
                    writer.WriteString("lastModifiedDateTime", edGraphServicesStateReportingV1EnvironmentListResponse.LastModifiedDateTime);
                else
                    writer.WriteNull("lastModifiedDateTime");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.TenantIdOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.TenantIdOption.Value != null)
                    writer.WriteString("tenantId", edGraphServicesStateReportingV1EnvironmentListResponse.TenantId);
                else
                    writer.WriteNull("tenantId");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.YearOption.IsSet)
                writer.WriteNumber("year", edGraphServicesStateReportingV1EnvironmentListResponse.YearOption.Value!.Value);

            if (edGraphServicesStateReportingV1EnvironmentListResponse.DbEnvironmentIdOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.DbEnvironmentIdOption.Value != null)
                    writer.WriteString("dbEnvironmentId", edGraphServicesStateReportingV1EnvironmentListResponse.DbEnvironmentId);
                else
                    writer.WriteNull("dbEnvironmentId");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.EdFiInstanceIdOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.EdFiInstanceIdOption.Value != null)
                    writer.WriteString("edFiInstanceId", edGraphServicesStateReportingV1EnvironmentListResponse.EdFiInstanceId);
                else
                    writer.WriteNull("edFiInstanceId");

            if (edGraphServicesStateReportingV1EnvironmentListResponse.ModeOption.IsSet)
                if (edGraphServicesStateReportingV1EnvironmentListResponse.ModeOption.Value != null)
                    writer.WriteString("mode", edGraphServicesStateReportingV1EnvironmentListResponse.Mode);
                else
                    writer.WriteNull("mode");
        }
    }
}
