// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole
    /// </summary>
    public partial class EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole" /> class.
        /// </summary>
        /// <param name="role">role</param>
        /// <param name="assignedPersonaIdentifiers">assignedPersonaIdentifiers</param>
        [JsonConstructor]
        public EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole(Option<string?> role = default, Option<List<string>?> assignedPersonaIdentifiers = default)
        {
            RoleOption = role;
            AssignedPersonaIdentifiersOption = assignedPersonaIdentifiers;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Role
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public string? Role { get { return this.RoleOption.Value; } set { this.RoleOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssignedPersonaIdentifiers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> AssignedPersonaIdentifiersOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssignedPersonaIdentifiers
        /// </summary>
        [JsonPropertyName("assignedPersonaIdentifiers")]
        public List<string>? AssignedPersonaIdentifiers { get { return this.AssignedPersonaIdentifiersOption.Value; } set { this.AssignedPersonaIdentifiersOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  AssignedPersonaIdentifiers: ").Append(AssignedPersonaIdentifiers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole" />
    /// </summary>
    public class EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRoleJsonConverter : JsonConverter<EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> role = default;
            Option<List<string>?> assignedPersonaIdentifiers = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "role":
                            role = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "assignedPersonaIdentifiers":
                            assignedPersonaIdentifiers = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole(role, assignedPersonaIdentifiers);
        }

        /// <summary>
        /// Serializes a <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole.RoleOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole.RoleOption.Value != null)
                    writer.WriteString("role", edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole.Role);
                else
                    writer.WriteNull("role");

            if (edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole.AssignedPersonaIdentifiersOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole.AssignedPersonaIdentifiersOption.Value != null)
                {
                    writer.WritePropertyName("assignedPersonaIdentifiers");
                    JsonSerializer.Serialize(writer, edGraphHttpAggregatorsTenantApiServicesObservationsStaffClassificationNamespaceRole.AssignedPersonaIdentifiers, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("assignedPersonaIdentifiers");
        }
    }
}
