// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse
    /// </summary>
    public partial class EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse" /> class.
        /// </summary>
        /// <param name="formId">formId</param>
        /// <param name="versions">versions</param>
        [JsonConstructor]
        public EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse(Option<string?> formId = default, Option<List<EdGraphHttpAggregatorsTenantApiServicesObservationsFormVersionConfigurationResponse>?> versions = default)
        {
            FormIdOption = formId;
            VersionsOption = versions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FormId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FormIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets FormId
        /// </summary>
        [JsonPropertyName("formId")]
        public string? FormId { get { return this.FormIdOption.Value; } set { this.FormIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Versions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EdGraphHttpAggregatorsTenantApiServicesObservationsFormVersionConfigurationResponse>?> VersionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Versions
        /// </summary>
        [JsonPropertyName("versions")]
        public List<EdGraphHttpAggregatorsTenantApiServicesObservationsFormVersionConfigurationResponse>? Versions { get { return this.VersionsOption.Value; } set { this.VersionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse {\n");
            sb.Append("  FormId: ").Append(FormId).Append("\n");
            sb.Append("  Versions: ").Append(Versions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse" />
    /// </summary>
    public class EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponseJsonConverter : JsonConverter<EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> formId = default;
            Option<List<EdGraphHttpAggregatorsTenantApiServicesObservationsFormVersionConfigurationResponse>?> versions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "formId":
                            formId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "versions":
                            versions = new Option<List<EdGraphHttpAggregatorsTenantApiServicesObservationsFormVersionConfigurationResponse>?>(JsonSerializer.Deserialize<List<EdGraphHttpAggregatorsTenantApiServicesObservationsFormVersionConfigurationResponse>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse(formId, versions);
        }

        /// <summary>
        /// Serializes a <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse.FormIdOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse.FormIdOption.Value != null)
                    writer.WriteString("formId", edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse.FormId);
                else
                    writer.WriteNull("formId");

            if (edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse.VersionsOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse.VersionsOption.Value != null)
                {
                    writer.WritePropertyName("versions");
                    JsonSerializer.Serialize(writer, edGraphHttpAggregatorsTenantApiServicesObservationsFormConfigurationResponse.Versions, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("versions");
        }
    }
}
