// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// One requirement, as embedded on the program. EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.RequirementRefDto.RequirementId is the requirements row.  EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.RequirementRefDto.IsRequired is copied from that row when the program is saved; false means optional.  EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.RequirementRefDto.Url is copied the same way, and set only on a &#x60;url&#x60; requirement.
    /// </summary>
    public partial class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="requirementId">requirementId</param>
        /// <param name="requirementType">requirementType</param>
        /// <param name="requirementCode">requirementCode</param>
        /// <param name="requirementTitle">requirementTitle</param>
        /// <param name="requirementDescription">requirementDescription</param>
        /// <param name="isUploadEnabled">isUploadEnabled</param>
        /// <param name="isRequired">isRequired</param>
        /// <param name="url">url</param>
        [JsonConstructor]
        public EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto(Option<Guid?> id = default, Option<Guid?> requirementId = default, Option<string?> requirementType = default, Option<string?> requirementCode = default, Option<string?> requirementTitle = default, Option<string?> requirementDescription = default, Option<bool?> isUploadEnabled = default, Option<bool?> isRequired = default, Option<string?> url = default)
        {
            IdOption = id;
            RequirementIdOption = requirementId;
            RequirementTypeOption = requirementType;
            RequirementCodeOption = requirementCode;
            RequirementTitleOption = requirementTitle;
            RequirementDescriptionOption = requirementDescription;
            IsUploadEnabledOption = isUploadEnabled;
            IsRequiredOption = isRequired;
            UrlOption = url;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequirementId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> RequirementIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequirementId
        /// </summary>
        [JsonPropertyName("requirementId")]
        public Guid? RequirementId { get { return this.RequirementIdOption.Value; } set { this.RequirementIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequirementType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequirementTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequirementType
        /// </summary>
        [JsonPropertyName("requirementType")]
        public string? RequirementType { get { return this.RequirementTypeOption.Value; } set { this.RequirementTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequirementCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequirementCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequirementCode
        /// </summary>
        [JsonPropertyName("requirementCode")]
        public string? RequirementCode { get { return this.RequirementCodeOption.Value; } set { this.RequirementCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequirementTitle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequirementTitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequirementTitle
        /// </summary>
        [JsonPropertyName("requirementTitle")]
        public string? RequirementTitle { get { return this.RequirementTitleOption.Value; } set { this.RequirementTitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequirementDescription
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequirementDescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequirementDescription
        /// </summary>
        [JsonPropertyName("requirementDescription")]
        public string? RequirementDescription { get { return this.RequirementDescriptionOption.Value; } set { this.RequirementDescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsUploadEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsUploadEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsUploadEnabled
        /// </summary>
        [JsonPropertyName("isUploadEnabled")]
        public bool? IsUploadEnabled { get { return this.IsUploadEnabledOption.Value; } set { this.IsUploadEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsRequired
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsRequiredOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsRequired
        /// </summary>
        [JsonPropertyName("isRequired")]
        public bool? IsRequired { get { return this.IsRequiredOption.Value; } set { this.IsRequiredOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption.Value; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RequirementId: ").Append(RequirementId).Append("\n");
            sb.Append("  RequirementType: ").Append(RequirementType).Append("\n");
            sb.Append("  RequirementCode: ").Append(RequirementCode).Append("\n");
            sb.Append("  RequirementTitle: ").Append(RequirementTitle).Append("\n");
            sb.Append("  RequirementDescription: ").Append(RequirementDescription).Append("\n");
            sb.Append("  IsUploadEnabled: ").Append(IsUploadEnabled).Append("\n");
            sb.Append("  IsRequired: ").Append(IsRequired).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto" />
    /// </summary>
    public class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDtoJsonConverter : JsonConverter<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> requirementId = default;
            Option<string?> requirementType = default;
            Option<string?> requirementCode = default;
            Option<string?> requirementTitle = default;
            Option<string?> requirementDescription = default;
            Option<bool?> isUploadEnabled = default;
            Option<bool?> isRequired = default;
            Option<string?> url = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "requirementId":
                            requirementId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "requirementType":
                            requirementType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "requirementCode":
                            requirementCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "requirementTitle":
                            requirementTitle = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "requirementDescription":
                            requirementDescription = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isUploadEnabled":
                            isUploadEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isRequired":
                            isRequired = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (isUploadEnabled.IsSet && isUploadEnabled.Value == null)
                throw new ArgumentNullException(nameof(isUploadEnabled), "Property is not nullable for class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.");

            if (isRequired.IsSet && isRequired.Value == null)
                throw new ArgumentNullException(nameof(isRequired), "Property is not nullable for class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.");

            return new EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto(id, requirementId, requirementType, requirementCode, requirementTitle, requirementDescription, isUploadEnabled, isRequired, url);
        }

        /// <summary>
        /// Serializes a <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.IdOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.IdOption.Value != null)
                    writer.WriteString("id", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.IdOption.Value!.Value);
                else
                    writer.WriteNull("id");

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementIdOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementIdOption.Value != null)
                    writer.WriteString("requirementId", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementIdOption.Value!.Value);
                else
                    writer.WriteNull("requirementId");

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementTypeOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementTypeOption.Value != null)
                    writer.WriteString("requirementType", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementType);
                else
                    writer.WriteNull("requirementType");

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementCodeOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementCodeOption.Value != null)
                    writer.WriteString("requirementCode", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementCode);
                else
                    writer.WriteNull("requirementCode");

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementTitleOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementTitleOption.Value != null)
                    writer.WriteString("requirementTitle", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementTitle);
                else
                    writer.WriteNull("requirementTitle");

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementDescriptionOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementDescriptionOption.Value != null)
                    writer.WriteString("requirementDescription", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.RequirementDescription);
                else
                    writer.WriteNull("requirementDescription");

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.IsUploadEnabledOption.IsSet)
                writer.WriteBoolean("isUploadEnabled", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.IsUploadEnabledOption.Value!.Value);

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.IsRequiredOption.IsSet)
                writer.WriteBoolean("isRequired", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.IsRequiredOption.Value!.Value);

            if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.UrlOption.IsSet)
                if (edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.UrlOption.Value != null)
                    writer.WriteString("url", edGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementRefDto.Url);
                else
                    writer.WriteNull("url");
        }
    }
}
