// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// One contact on a registration. id is the entry&#39;s own identity (minted once, never overwritten);  contactId is the EnrollmentContact record id the entry resolved to (the key every join goes  through; unset until resolved); externalDataSourceContactId is the SIS-side code, when known.
    /// </summary>
    public partial class EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="contactId">contactId</param>
        /// <param name="contactName">contactName</param>
        /// <param name="contactPhone">contactPhone</param>
        /// <param name="contactEmail">contactEmail</param>
        /// <param name="externalDataSourceContactId">externalDataSourceContactId</param>
        [JsonConstructor]
        public EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage(Option<string?> id = default, Option<string?> contactId = default, Option<string?> contactName = default, Option<string?> contactPhone = default, Option<string?> contactEmail = default, Option<string?> externalDataSourceContactId = default)
        {
            IdOption = id;
            ContactIdOption = contactId;
            ContactNameOption = contactName;
            ContactPhoneOption = contactPhone;
            ContactEmailOption = contactEmail;
            ExternalDataSourceContactIdOption = externalDataSourceContactId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContactId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContactId
        /// </summary>
        [JsonPropertyName("contactId")]
        public string? ContactId { get { return this.ContactIdOption.Value; } set { this.ContactIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContactName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContactName
        /// </summary>
        [JsonPropertyName("contactName")]
        public string? ContactName { get { return this.ContactNameOption.Value; } set { this.ContactNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContactPhone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactPhoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContactPhone
        /// </summary>
        [JsonPropertyName("contactPhone")]
        public string? ContactPhone { get { return this.ContactPhoneOption.Value; } set { this.ContactPhoneOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContactEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactEmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContactEmail
        /// </summary>
        [JsonPropertyName("contactEmail")]
        public string? ContactEmail { get { return this.ContactEmailOption.Value; } set { this.ContactEmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalDataSourceContactId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalDataSourceContactIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalDataSourceContactId
        /// </summary>
        [JsonPropertyName("externalDataSourceContactId")]
        public string? ExternalDataSourceContactId { get { return this.ExternalDataSourceContactIdOption.Value; } set { this.ExternalDataSourceContactIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("  ContactName: ").Append(ContactName).Append("\n");
            sb.Append("  ContactPhone: ").Append(ContactPhone).Append("\n");
            sb.Append("  ContactEmail: ").Append(ContactEmail).Append("\n");
            sb.Append("  ExternalDataSourceContactId: ").Append(ExternalDataSourceContactId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage" />
    /// </summary>
    public class EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessageJsonConverter : JsonConverter<EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> contactId = default;
            Option<string?> contactName = default;
            Option<string?> contactPhone = default;
            Option<string?> contactEmail = default;
            Option<string?> externalDataSourceContactId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contactId":
                            contactId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contactName":
                            contactName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contactPhone":
                            contactPhone = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contactEmail":
                            contactEmail = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "externalDataSourceContactId":
                            externalDataSourceContactId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage(id, contactId, contactName, contactPhone, contactEmail, externalDataSourceContactId);
        }

        /// <summary>
        /// Serializes a <see cref="EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.IdOption.IsSet)
                if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.IdOption.Value != null)
                    writer.WriteString("id", enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.Id);
                else
                    writer.WriteNull("id");

            if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactIdOption.IsSet)
                if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactIdOption.Value != null)
                    writer.WriteString("contactId", enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactId);
                else
                    writer.WriteNull("contactId");

            if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactNameOption.IsSet)
                if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactNameOption.Value != null)
                    writer.WriteString("contactName", enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactName);
                else
                    writer.WriteNull("contactName");

            if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactPhoneOption.IsSet)
                if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactPhoneOption.Value != null)
                    writer.WriteString("contactPhone", enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactPhone);
                else
                    writer.WriteNull("contactPhone");

            if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactEmailOption.IsSet)
                if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactEmailOption.Value != null)
                    writer.WriteString("contactEmail", enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ContactEmail);
                else
                    writer.WriteNull("contactEmail");

            if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ExternalDataSourceContactIdOption.IsSet)
                if (enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ExternalDataSourceContactIdOption.Value != null)
                    writer.WriteString("externalDataSourceContactId", enrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage.ExternalDataSourceContactId);
                else
                    writer.WriteNull("externalDataSourceContactId");
        }
    }
}
