// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// FormApiFormsV1CreateFormRequest
    /// </summary>
    public partial class FormApiFormsV1CreateFormRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FormApiFormsV1CreateFormRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="description">description</param>
        /// <param name="source">source</param>
        /// <param name="varVersion">varVersion</param>
        /// <param name="anonymous">anonymous</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="status">status</param>
        /// <param name="image">image</param>
        [JsonConstructor]
        public FormApiFormsV1CreateFormRequest(Option<string?> name = default, Option<string?> description = default, Option<FormApiFormsV1FormSource?> source = default, Option<string?> varVersion = default, Option<bool?> anonymous = default, Option<string?> tenantId = default, Option<FormApiFormsV1FormStatus?> status = default, Option<string?> image = default)
        {
            NameOption = name;
            DescriptionOption = description;
            SourceOption = source;
            VarVersionOption = varVersion;
            AnonymousOption = anonymous;
            TenantIdOption = tenantId;
            StatusOption = status;
            ImageOption = image;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FormApiFormsV1FormSource?> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public FormApiFormsV1FormSource? Source { get { return this.SourceOption.Value; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FormApiFormsV1FormStatus?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public FormApiFormsV1FormStatus? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of VarVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VarVersionOption { get; private set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [JsonPropertyName("version")]
        public string? VarVersion { get { return this.VarVersionOption.Value; } set { this.VarVersionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Anonymous
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AnonymousOption { get; private set; }

        /// <summary>
        /// Gets or Sets Anonymous
        /// </summary>
        [JsonPropertyName("anonymous")]
        public bool? Anonymous { get { return this.AnonymousOption.Value; } set { this.AnonymousOption = new(value); } }

        /// <summary>
        /// Used to track the state of TenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string? TenantId { get { return this.TenantIdOption.Value; } set { this.TenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Image
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [JsonPropertyName("image")]
        public string? Image { get { return this.ImageOption.Value; } set { this.ImageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FormApiFormsV1CreateFormRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Anonymous: ").Append(Anonymous).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FormApiFormsV1CreateFormRequest" />
    /// </summary>
    public class FormApiFormsV1CreateFormRequestJsonConverter : JsonConverter<FormApiFormsV1CreateFormRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="FormApiFormsV1CreateFormRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FormApiFormsV1CreateFormRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> description = default;
            Option<FormApiFormsV1FormSource?> source = default;
            Option<string?> varVersion = default;
            Option<bool?> anonymous = default;
            Option<string?> tenantId = default;
            Option<FormApiFormsV1FormStatus?> status = default;
            Option<string?> image = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "source":
                            string? sourceRawValue = utf8JsonReader.GetString();
                            if (sourceRawValue != null)
                                source = new Option<FormApiFormsV1FormSource?>(FormApiFormsV1FormSourceValueConverter.FromStringOrDefault(sourceRawValue));
                            break;
                        case "version":
                            varVersion = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "anonymous":
                            anonymous = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<FormApiFormsV1FormStatus?>(FormApiFormsV1FormStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "image":
                            image = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class FormApiFormsV1CreateFormRequest.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class FormApiFormsV1CreateFormRequest.");

            return new FormApiFormsV1CreateFormRequest(name, description, source, varVersion, anonymous, tenantId, status, image);
        }

        /// <summary>
        /// Serializes a <see cref="FormApiFormsV1CreateFormRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="formApiFormsV1CreateFormRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FormApiFormsV1CreateFormRequest formApiFormsV1CreateFormRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, formApiFormsV1CreateFormRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FormApiFormsV1CreateFormRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="formApiFormsV1CreateFormRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FormApiFormsV1CreateFormRequest formApiFormsV1CreateFormRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (formApiFormsV1CreateFormRequest.NameOption.IsSet)
                if (formApiFormsV1CreateFormRequest.NameOption.Value != null)
                    writer.WriteString("name", formApiFormsV1CreateFormRequest.Name);
                else
                    writer.WriteNull("name");

            if (formApiFormsV1CreateFormRequest.DescriptionOption.IsSet)
                if (formApiFormsV1CreateFormRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", formApiFormsV1CreateFormRequest.Description);
                else
                    writer.WriteNull("description");

            if (formApiFormsV1CreateFormRequest.SourceOption.IsSet)
            {
                var sourceRawValue = FormApiFormsV1FormSourceValueConverter.ToJsonValue(formApiFormsV1CreateFormRequest.Source!.Value);
                writer.WriteString("source", sourceRawValue);
            }
            if (formApiFormsV1CreateFormRequest.VarVersionOption.IsSet)
                if (formApiFormsV1CreateFormRequest.VarVersionOption.Value != null)
                    writer.WriteString("version", formApiFormsV1CreateFormRequest.VarVersion);
                else
                    writer.WriteNull("version");

            if (formApiFormsV1CreateFormRequest.AnonymousOption.IsSet)
                if (formApiFormsV1CreateFormRequest.AnonymousOption.Value != null)
                    writer.WriteBoolean("anonymous", formApiFormsV1CreateFormRequest.AnonymousOption.Value!.Value);
                else
                    writer.WriteNull("anonymous");

            if (formApiFormsV1CreateFormRequest.TenantIdOption.IsSet)
                if (formApiFormsV1CreateFormRequest.TenantIdOption.Value != null)
                    writer.WriteString("tenantId", formApiFormsV1CreateFormRequest.TenantId);
                else
                    writer.WriteNull("tenantId");

            if (formApiFormsV1CreateFormRequest.StatusOption.IsSet)
            {
                var statusRawValue = FormApiFormsV1FormStatusValueConverter.ToJsonValue(formApiFormsV1CreateFormRequest.Status!.Value);
                writer.WriteString("status", statusRawValue);
            }
            if (formApiFormsV1CreateFormRequest.ImageOption.IsSet)
                if (formApiFormsV1CreateFormRequest.ImageOption.Value != null)
                    writer.WriteString("image", formApiFormsV1CreateFormRequest.Image);
                else
                    writer.WriteNull("image");
        }
    }
}
