// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// IdentityApiUserV2UserLicenseProfileResponse
    /// </summary>
    public partial class IdentityApiUserV2UserLicenseProfileResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IdentityApiUserV2UserLicenseProfileResponse" /> class.
        /// </summary>
        /// <param name="applicationId">applicationId</param>
        /// <param name="applicationName">applicationName</param>
        /// <param name="role">role</param>
        /// <param name="licenseStatus">licenseStatus</param>
        /// <param name="licenseSource">licenseSource</param>
        /// <param name="educationOrganizationId">educationOrganizationId</param>
        /// <param name="educationOrganizationSource">educationOrganizationSource</param>
        /// <param name="staffClassification">staffClassification</param>
        [JsonConstructor]
        public IdentityApiUserV2UserLicenseProfileResponse(Option<string?> applicationId = default, Option<string?> applicationName = default, Option<IdentityApiUserV2UserLicenseRole?> role = default, Option<string?> licenseStatus = default, Option<string?> licenseSource = default, Option<int?> educationOrganizationId = default, Option<string?> educationOrganizationSource = default, Option<string?> staffClassification = default)
        {
            ApplicationIdOption = applicationId;
            ApplicationNameOption = applicationName;
            RoleOption = role;
            LicenseStatusOption = licenseStatus;
            LicenseSourceOption = licenseSource;
            EducationOrganizationIdOption = educationOrganizationId;
            EducationOrganizationSourceOption = educationOrganizationSource;
            StaffClassificationOption = staffClassification;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ApplicationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ApplicationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplicationId
        /// </summary>
        [JsonPropertyName("applicationId")]
        public string? ApplicationId { get { return this.ApplicationIdOption.Value; } set { this.ApplicationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApplicationName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ApplicationNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplicationName
        /// </summary>
        [JsonPropertyName("applicationName")]
        public string? ApplicationName { get { return this.ApplicationNameOption.Value; } set { this.ApplicationNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Role
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IdentityApiUserV2UserLicenseRole?> RoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public IdentityApiUserV2UserLicenseRole? Role { get { return this.RoleOption.Value; } set { this.RoleOption = new(value); } }

        /// <summary>
        /// Used to track the state of LicenseStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LicenseStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets LicenseStatus
        /// </summary>
        [JsonPropertyName("licenseStatus")]
        public string? LicenseStatus { get { return this.LicenseStatusOption.Value; } set { this.LicenseStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of LicenseSource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LicenseSourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets LicenseSource
        /// </summary>
        [JsonPropertyName("licenseSource")]
        public string? LicenseSource { get { return this.LicenseSourceOption.Value; } set { this.LicenseSourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of EducationOrganizationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EducationOrganizationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EducationOrganizationId
        /// </summary>
        [JsonPropertyName("educationOrganizationId")]
        public int? EducationOrganizationId { get { return this.EducationOrganizationIdOption.Value; } set { this.EducationOrganizationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of EducationOrganizationSource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EducationOrganizationSourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets EducationOrganizationSource
        /// </summary>
        [JsonPropertyName("educationOrganizationSource")]
        public string? EducationOrganizationSource { get { return this.EducationOrganizationSourceOption.Value; } set { this.EducationOrganizationSourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of StaffClassification
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StaffClassificationOption { get; private set; }

        /// <summary>
        /// Gets or Sets StaffClassification
        /// </summary>
        [JsonPropertyName("staffClassification")]
        public string? StaffClassification { get { return this.StaffClassificationOption.Value; } set { this.StaffClassificationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IdentityApiUserV2UserLicenseProfileResponse {\n");
            sb.Append("  ApplicationId: ").Append(ApplicationId).Append("\n");
            sb.Append("  ApplicationName: ").Append(ApplicationName).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  LicenseStatus: ").Append(LicenseStatus).Append("\n");
            sb.Append("  LicenseSource: ").Append(LicenseSource).Append("\n");
            sb.Append("  EducationOrganizationId: ").Append(EducationOrganizationId).Append("\n");
            sb.Append("  EducationOrganizationSource: ").Append(EducationOrganizationSource).Append("\n");
            sb.Append("  StaffClassification: ").Append(StaffClassification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IdentityApiUserV2UserLicenseProfileResponse" />
    /// </summary>
    public class IdentityApiUserV2UserLicenseProfileResponseJsonConverter : JsonConverter<IdentityApiUserV2UserLicenseProfileResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="IdentityApiUserV2UserLicenseProfileResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IdentityApiUserV2UserLicenseProfileResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> applicationId = default;
            Option<string?> applicationName = default;
            Option<IdentityApiUserV2UserLicenseRole?> role = default;
            Option<string?> licenseStatus = default;
            Option<string?> licenseSource = default;
            Option<int?> educationOrganizationId = default;
            Option<string?> educationOrganizationSource = default;
            Option<string?> staffClassification = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "applicationId":
                            applicationId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "applicationName":
                            applicationName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "role":
                            role = new Option<IdentityApiUserV2UserLicenseRole?>(JsonSerializer.Deserialize<IdentityApiUserV2UserLicenseRole>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "licenseStatus":
                            licenseStatus = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "licenseSource":
                            licenseSource = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "educationOrganizationId":
                            educationOrganizationId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "educationOrganizationSource":
                            educationOrganizationSource = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "staffClassification":
                            staffClassification = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (role.IsSet && role.Value == null)
                throw new ArgumentNullException(nameof(role), "Property is not nullable for class IdentityApiUserV2UserLicenseProfileResponse.");

            return new IdentityApiUserV2UserLicenseProfileResponse(applicationId, applicationName, role, licenseStatus, licenseSource, educationOrganizationId, educationOrganizationSource, staffClassification);
        }

        /// <summary>
        /// Serializes a <see cref="IdentityApiUserV2UserLicenseProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="identityApiUserV2UserLicenseProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IdentityApiUserV2UserLicenseProfileResponse identityApiUserV2UserLicenseProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, identityApiUserV2UserLicenseProfileResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IdentityApiUserV2UserLicenseProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="identityApiUserV2UserLicenseProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IdentityApiUserV2UserLicenseProfileResponse identityApiUserV2UserLicenseProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (identityApiUserV2UserLicenseProfileResponse.RoleOption.IsSet && identityApiUserV2UserLicenseProfileResponse.Role == null)
                throw new ArgumentNullException(nameof(identityApiUserV2UserLicenseProfileResponse.Role), "Property is required for class IdentityApiUserV2UserLicenseProfileResponse.");

            if (identityApiUserV2UserLicenseProfileResponse.ApplicationIdOption.IsSet)
                if (identityApiUserV2UserLicenseProfileResponse.ApplicationIdOption.Value != null)
                    writer.WriteString("applicationId", identityApiUserV2UserLicenseProfileResponse.ApplicationId);
                else
                    writer.WriteNull("applicationId");

            if (identityApiUserV2UserLicenseProfileResponse.ApplicationNameOption.IsSet)
                if (identityApiUserV2UserLicenseProfileResponse.ApplicationNameOption.Value != null)
                    writer.WriteString("applicationName", identityApiUserV2UserLicenseProfileResponse.ApplicationName);
                else
                    writer.WriteNull("applicationName");

            if (identityApiUserV2UserLicenseProfileResponse.RoleOption.IsSet)
            {
                writer.WritePropertyName("role");
                JsonSerializer.Serialize(writer, identityApiUserV2UserLicenseProfileResponse.Role, jsonSerializerOptions);
            }
            if (identityApiUserV2UserLicenseProfileResponse.LicenseStatusOption.IsSet)
                if (identityApiUserV2UserLicenseProfileResponse.LicenseStatusOption.Value != null)
                    writer.WriteString("licenseStatus", identityApiUserV2UserLicenseProfileResponse.LicenseStatus);
                else
                    writer.WriteNull("licenseStatus");

            if (identityApiUserV2UserLicenseProfileResponse.LicenseSourceOption.IsSet)
                if (identityApiUserV2UserLicenseProfileResponse.LicenseSourceOption.Value != null)
                    writer.WriteString("licenseSource", identityApiUserV2UserLicenseProfileResponse.LicenseSource);
                else
                    writer.WriteNull("licenseSource");

            if (identityApiUserV2UserLicenseProfileResponse.EducationOrganizationIdOption.IsSet)
                if (identityApiUserV2UserLicenseProfileResponse.EducationOrganizationIdOption.Value != null)
                    writer.WriteNumber("educationOrganizationId", identityApiUserV2UserLicenseProfileResponse.EducationOrganizationIdOption.Value!.Value);
                else
                    writer.WriteNull("educationOrganizationId");

            if (identityApiUserV2UserLicenseProfileResponse.EducationOrganizationSourceOption.IsSet)
                if (identityApiUserV2UserLicenseProfileResponse.EducationOrganizationSourceOption.Value != null)
                    writer.WriteString("educationOrganizationSource", identityApiUserV2UserLicenseProfileResponse.EducationOrganizationSource);
                else
                    writer.WriteNull("educationOrganizationSource");

            if (identityApiUserV2UserLicenseProfileResponse.StaffClassificationOption.IsSet)
                if (identityApiUserV2UserLicenseProfileResponse.StaffClassificationOption.Value != null)
                    writer.WriteString("staffClassification", identityApiUserV2UserLicenseProfileResponse.StaffClassification);
                else
                    writer.WriteNull("staffClassification");
        }
    }
}
