// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// Defines IMSAdminApi.V1.Clients.TokenExpiration
    /// </summary>
    public enum IMSAdminApiV1ClientsTokenExpiration
    {
        /// <summary>
        /// Enum Sliding for value: Sliding
        /// </summary>
        Sliding = 1,

        /// <summary>
        /// Enum Absolute for value: Absolute
        /// </summary>
        Absolute = 2
    }

    /// <summary>
    /// Converts <see cref="IMSAdminApiV1ClientsTokenExpiration"/> to and from the JSON value
    /// </summary>
    public static class IMSAdminApiV1ClientsTokenExpirationValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="IMSAdminApiV1ClientsTokenExpiration"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IMSAdminApiV1ClientsTokenExpiration FromString(string value)
        {
            if (value.Equals("Sliding"))
                return IMSAdminApiV1ClientsTokenExpiration.Sliding;

            if (value.Equals("Absolute"))
                return IMSAdminApiV1ClientsTokenExpiration.Absolute;

            throw new NotImplementedException($"Could not convert value to type IMSAdminApiV1ClientsTokenExpiration: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="IMSAdminApiV1ClientsTokenExpiration"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IMSAdminApiV1ClientsTokenExpiration? FromStringOrDefault(string value)
        {
            if (value.Equals("Sliding"))
                return IMSAdminApiV1ClientsTokenExpiration.Sliding;

            if (value.Equals("Absolute"))
                return IMSAdminApiV1ClientsTokenExpiration.Absolute;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="IMSAdminApiV1ClientsTokenExpiration"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(IMSAdminApiV1ClientsTokenExpiration value)
        {
            if (value == IMSAdminApiV1ClientsTokenExpiration.Sliding)
                return "Sliding";

            if (value == IMSAdminApiV1ClientsTokenExpiration.Absolute)
                return "Absolute";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IMSAdminApiV1ClientsTokenExpiration"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class IMSAdminApiV1ClientsTokenExpirationJsonConverter : JsonConverter<IMSAdminApiV1ClientsTokenExpiration>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IMSAdminApiV1ClientsTokenExpiration Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IMSAdminApiV1ClientsTokenExpiration? result = rawValue == null
                ? null
                : IMSAdminApiV1ClientsTokenExpirationValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IMSAdminApiV1ClientsTokenExpiration to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="iMSAdminApiV1ClientsTokenExpiration"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IMSAdminApiV1ClientsTokenExpiration iMSAdminApiV1ClientsTokenExpiration, JsonSerializerOptions options)
        {
            writer.WriteStringValue(iMSAdminApiV1ClientsTokenExpiration.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IMSAdminApiV1ClientsTokenExpiration"/>
    /// </summary>
    public class IMSAdminApiV1ClientsTokenExpirationNullableJsonConverter : JsonConverter<IMSAdminApiV1ClientsTokenExpiration?>
    {
        /// <summary>
        /// Returns a IMSAdminApiV1ClientsTokenExpiration from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IMSAdminApiV1ClientsTokenExpiration? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            IMSAdminApiV1ClientsTokenExpiration? result = rawValue == null
                ? null
                : IMSAdminApiV1ClientsTokenExpirationValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="iMSAdminApiV1ClientsTokenExpiration"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IMSAdminApiV1ClientsTokenExpiration? iMSAdminApiV1ClientsTokenExpiration, JsonSerializerOptions options)
        {
            writer.WriteStringValue(iMSAdminApiV1ClientsTokenExpiration?.ToString() ?? "null");
        }
    }
}
