// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// TenantApiWebhookV1WebhookEventResponse
    /// </summary>
    public partial class TenantApiWebhookV1WebhookEventResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantApiWebhookV1WebhookEventResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="createdBy">createdBy</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="updatedBy">updatedBy</param>
        /// <param name="isDeleted">isDeleted</param>
        /// <param name="provider">provider</param>
        /// <param name="group">group</param>
        /// <param name="name">name</param>
        /// <param name="displayName">displayName</param>
        /// <param name="scope">scope</param>
        [JsonConstructor]
        public TenantApiWebhookV1WebhookEventResponse(Option<string?> id = default, Option<string?> createdAt = default, Option<string?> createdBy = default, Option<string?> updatedAt = default, Option<string?> updatedBy = default, Option<bool?> isDeleted = default, Option<string?> provider = default, Option<string?> group = default, Option<string?> name = default, Option<string?> displayName = default, Option<List<string>?> scope = default)
        {
            IdOption = id;
            CreatedAtOption = createdAt;
            CreatedByOption = createdBy;
            UpdatedAtOption = updatedAt;
            UpdatedByOption = updatedBy;
            IsDeletedOption = isDeleted;
            ProviderOption = provider;
            GroupOption = group;
            NameOption = name;
            DisplayNameOption = displayName;
            ScopeOption = scope;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public string? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [JsonPropertyName("createdBy")]
        public string? CreatedBy { get { return this.CreatedByOption.Value; } set { this.CreatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public string? UpdatedAt { get { return this.UpdatedAtOption.Value; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpdatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedBy
        /// </summary>
        [JsonPropertyName("updatedBy")]
        public string? UpdatedBy { get { return this.UpdatedByOption.Value; } set { this.UpdatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsDeleted
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsDeletedOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsDeleted
        /// </summary>
        [JsonPropertyName("isDeleted")]
        public bool? IsDeleted { get { return this.IsDeletedOption.Value; } set { this.IsDeletedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Provider
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProviderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [JsonPropertyName("provider")]
        public string? Provider { get { return this.ProviderOption.Value; } set { this.ProviderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Group
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GroupOption { get; private set; }

        /// <summary>
        /// Gets or Sets Group
        /// </summary>
        [JsonPropertyName("group")]
        public string? Group { get { return this.GroupOption.Value; } set { this.GroupOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of DisplayName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DisplayNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [JsonPropertyName("displayName")]
        public string? DisplayName { get { return this.DisplayNameOption.Value; } set { this.DisplayNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Scope
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ScopeOption { get; }

        /// <summary>
        /// Gets or Sets Scope
        /// </summary>
        [JsonPropertyName("scope")]
        public List<string>? Scope { get { return this.ScopeOption.Value; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantApiWebhookV1WebhookEventResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantApiWebhookV1WebhookEventResponse" />
    /// </summary>
    public class TenantApiWebhookV1WebhookEventResponseJsonConverter : JsonConverter<TenantApiWebhookV1WebhookEventResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="TenantApiWebhookV1WebhookEventResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TenantApiWebhookV1WebhookEventResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> createdAt = default;
            Option<string?> createdBy = default;
            Option<string?> updatedAt = default;
            Option<string?> updatedBy = default;
            Option<bool?> isDeleted = default;
            Option<string?> provider = default;
            Option<string?> group = default;
            Option<string?> name = default;
            Option<string?> displayName = default;
            Option<List<string>?> scope = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "createdAt":
                            createdAt = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "createdBy":
                            createdBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "updatedAt":
                            updatedAt = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "updatedBy":
                            updatedBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isDeleted":
                            isDeleted = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "provider":
                            provider = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "group":
                            group = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "displayName":
                            displayName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "scope":
                            scope = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (isDeleted.IsSet && isDeleted.Value == null)
                throw new ArgumentNullException(nameof(isDeleted), "Property is not nullable for class TenantApiWebhookV1WebhookEventResponse.");

            return new TenantApiWebhookV1WebhookEventResponse(id, createdAt, createdBy, updatedAt, updatedBy, isDeleted, provider, group, name, displayName, scope);
        }

        /// <summary>
        /// Serializes a <see cref="TenantApiWebhookV1WebhookEventResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantApiWebhookV1WebhookEventResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TenantApiWebhookV1WebhookEventResponse tenantApiWebhookV1WebhookEventResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tenantApiWebhookV1WebhookEventResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TenantApiWebhookV1WebhookEventResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantApiWebhookV1WebhookEventResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TenantApiWebhookV1WebhookEventResponse tenantApiWebhookV1WebhookEventResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tenantApiWebhookV1WebhookEventResponse.IdOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.IdOption.Value != null)
                    writer.WriteString("id", tenantApiWebhookV1WebhookEventResponse.Id);
                else
                    writer.WriteNull("id");

            if (tenantApiWebhookV1WebhookEventResponse.CreatedAtOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.CreatedAtOption.Value != null)
                    writer.WriteString("createdAt", tenantApiWebhookV1WebhookEventResponse.CreatedAt);
                else
                    writer.WriteNull("createdAt");

            if (tenantApiWebhookV1WebhookEventResponse.CreatedByOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.CreatedByOption.Value != null)
                    writer.WriteString("createdBy", tenantApiWebhookV1WebhookEventResponse.CreatedBy);
                else
                    writer.WriteNull("createdBy");

            if (tenantApiWebhookV1WebhookEventResponse.UpdatedAtOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.UpdatedAtOption.Value != null)
                    writer.WriteString("updatedAt", tenantApiWebhookV1WebhookEventResponse.UpdatedAt);
                else
                    writer.WriteNull("updatedAt");

            if (tenantApiWebhookV1WebhookEventResponse.UpdatedByOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.UpdatedByOption.Value != null)
                    writer.WriteString("updatedBy", tenantApiWebhookV1WebhookEventResponse.UpdatedBy);
                else
                    writer.WriteNull("updatedBy");

            if (tenantApiWebhookV1WebhookEventResponse.IsDeletedOption.IsSet)
                writer.WriteBoolean("isDeleted", tenantApiWebhookV1WebhookEventResponse.IsDeletedOption.Value!.Value);

            if (tenantApiWebhookV1WebhookEventResponse.ProviderOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.ProviderOption.Value != null)
                    writer.WriteString("provider", tenantApiWebhookV1WebhookEventResponse.Provider);
                else
                    writer.WriteNull("provider");

            if (tenantApiWebhookV1WebhookEventResponse.GroupOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.GroupOption.Value != null)
                    writer.WriteString("group", tenantApiWebhookV1WebhookEventResponse.Group);
                else
                    writer.WriteNull("group");

            if (tenantApiWebhookV1WebhookEventResponse.NameOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.NameOption.Value != null)
                    writer.WriteString("name", tenantApiWebhookV1WebhookEventResponse.Name);
                else
                    writer.WriteNull("name");

            if (tenantApiWebhookV1WebhookEventResponse.DisplayNameOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.DisplayNameOption.Value != null)
                    writer.WriteString("displayName", tenantApiWebhookV1WebhookEventResponse.DisplayName);
                else
                    writer.WriteNull("displayName");

            if (tenantApiWebhookV1WebhookEventResponse.ScopeOption.IsSet)
                if (tenantApiWebhookV1WebhookEventResponse.ScopeOption.Value != null)
                {
                    writer.WritePropertyName("scope");
                    JsonSerializer.Serialize(writer, tenantApiWebhookV1WebhookEventResponse.Scope, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("scope");
        }
    }
}
