// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// ValidationsApiContainersV1AddDataStewardRequest
    /// </summary>
    public partial class ValidationsApiContainersV1AddDataStewardRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationsApiContainersV1AddDataStewardRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId</param>
        /// <param name="collectionId">collectionId</param>
        /// <param name="email">email</param>
        /// <param name="firstName">firstName</param>
        /// <param name="lastName">lastName</param>
        /// <param name="userId">userId</param>
        /// <param name="reportingPeriodId">reportingPeriodId</param>
        /// <param name="environmentId">environmentId</param>
        [JsonConstructor]
        public ValidationsApiContainersV1AddDataStewardRequest(Option<string?> tenantId = default, Option<string?> collectionId = default, Option<string?> email = default, Option<string?> firstName = default, Option<string?> lastName = default, Option<string?> userId = default, Option<string?> reportingPeriodId = default, Option<string?> environmentId = default)
        {
            TenantIdOption = tenantId;
            CollectionIdOption = collectionId;
            EmailOption = email;
            FirstNameOption = firstName;
            LastNameOption = lastName;
            UserIdOption = userId;
            ReportingPeriodIdOption = reportingPeriodId;
            EnvironmentIdOption = environmentId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string? TenantId { get { return this.TenantIdOption.Value; } set { this.TenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CollectionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CollectionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CollectionId
        /// </summary>
        [JsonPropertyName("collectionId")]
        public string? CollectionId { get { return this.CollectionIdOption.Value; } set { this.CollectionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of FirstName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FirstNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [JsonPropertyName("firstName")]
        public string? FirstName { get { return this.FirstNameOption.Value; } set { this.FirstNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [JsonPropertyName("lastName")]
        public string? LastName { get { return this.LastNameOption.Value; } set { this.LastNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("userId")]
        public string? UserId { get { return this.UserIdOption.Value; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReportingPeriodId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReportingPeriodIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReportingPeriodId
        /// </summary>
        [JsonPropertyName("reportingPeriodId")]
        public string? ReportingPeriodId { get { return this.ReportingPeriodIdOption.Value; } set { this.ReportingPeriodIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnvironmentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EnvironmentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnvironmentId
        /// </summary>
        [JsonPropertyName("environmentId")]
        public string? EnvironmentId { get { return this.EnvironmentIdOption.Value; } set { this.EnvironmentIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationsApiContainersV1AddDataStewardRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  CollectionId: ").Append(CollectionId).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  ReportingPeriodId: ").Append(ReportingPeriodId).Append("\n");
            sb.Append("  EnvironmentId: ").Append(EnvironmentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ValidationsApiContainersV1AddDataStewardRequest" />
    /// </summary>
    public class ValidationsApiContainersV1AddDataStewardRequestJsonConverter : JsonConverter<ValidationsApiContainersV1AddDataStewardRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ValidationsApiContainersV1AddDataStewardRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ValidationsApiContainersV1AddDataStewardRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> tenantId = default;
            Option<string?> collectionId = default;
            Option<string?> email = default;
            Option<string?> firstName = default;
            Option<string?> lastName = default;
            Option<string?> userId = default;
            Option<string?> reportingPeriodId = default;
            Option<string?> environmentId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "collectionId":
                            collectionId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "firstName":
                            firstName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastName":
                            lastName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "userId":
                            userId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "reportingPeriodId":
                            reportingPeriodId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "environmentId":
                            environmentId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ValidationsApiContainersV1AddDataStewardRequest(tenantId, collectionId, email, firstName, lastName, userId, reportingPeriodId, environmentId);
        }

        /// <summary>
        /// Serializes a <see cref="ValidationsApiContainersV1AddDataStewardRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationsApiContainersV1AddDataStewardRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ValidationsApiContainersV1AddDataStewardRequest validationsApiContainersV1AddDataStewardRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, validationsApiContainersV1AddDataStewardRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ValidationsApiContainersV1AddDataStewardRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationsApiContainersV1AddDataStewardRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ValidationsApiContainersV1AddDataStewardRequest validationsApiContainersV1AddDataStewardRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (validationsApiContainersV1AddDataStewardRequest.TenantIdOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.TenantIdOption.Value != null)
                    writer.WriteString("tenantId", validationsApiContainersV1AddDataStewardRequest.TenantId);
                else
                    writer.WriteNull("tenantId");

            if (validationsApiContainersV1AddDataStewardRequest.CollectionIdOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.CollectionIdOption.Value != null)
                    writer.WriteString("collectionId", validationsApiContainersV1AddDataStewardRequest.CollectionId);
                else
                    writer.WriteNull("collectionId");

            if (validationsApiContainersV1AddDataStewardRequest.EmailOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.EmailOption.Value != null)
                    writer.WriteString("email", validationsApiContainersV1AddDataStewardRequest.Email);
                else
                    writer.WriteNull("email");

            if (validationsApiContainersV1AddDataStewardRequest.FirstNameOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.FirstNameOption.Value != null)
                    writer.WriteString("firstName", validationsApiContainersV1AddDataStewardRequest.FirstName);
                else
                    writer.WriteNull("firstName");

            if (validationsApiContainersV1AddDataStewardRequest.LastNameOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.LastNameOption.Value != null)
                    writer.WriteString("lastName", validationsApiContainersV1AddDataStewardRequest.LastName);
                else
                    writer.WriteNull("lastName");

            if (validationsApiContainersV1AddDataStewardRequest.UserIdOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.UserIdOption.Value != null)
                    writer.WriteString("userId", validationsApiContainersV1AddDataStewardRequest.UserId);
                else
                    writer.WriteNull("userId");

            if (validationsApiContainersV1AddDataStewardRequest.ReportingPeriodIdOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.ReportingPeriodIdOption.Value != null)
                    writer.WriteString("reportingPeriodId", validationsApiContainersV1AddDataStewardRequest.ReportingPeriodId);
                else
                    writer.WriteNull("reportingPeriodId");

            if (validationsApiContainersV1AddDataStewardRequest.EnvironmentIdOption.IsSet)
                if (validationsApiContainersV1AddDataStewardRequest.EnvironmentIdOption.Value != null)
                    writer.WriteString("environmentId", validationsApiContainersV1AddDataStewardRequest.EnvironmentId);
                else
                    writer.WriteNull("environmentId");
        }
    }
}
