// <auto-generated>
/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule
    /// </summary>
    public partial class ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="identification">identification</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule(Option<string?> id = default, Option<string?> identification = default, Option<string?> name = default)
        {
            IdOption = id;
            IdentificationOption = identification;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Identification
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdentificationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Identification
        /// </summary>
        [JsonPropertyName("identification")]
        public string? Identification { get { return this.IdentificationOption; } set { this.IdentificationOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Identification: ").Append(Identification).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule" />
    /// </summary>
    public class ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRuleJsonConverter : JsonConverter<ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule>
    {
        /// <summary>
        /// Deserializes json to <see cref="ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> identification = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "identification":
                            identification = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule(id, identification, name);
        }

        /// <summary>
        /// Serializes a <see cref="ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ValidationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule, JsonSerializerOptions jsonSerializerOptions)
        {
            if (validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.IdOption.IsSet)
                if (validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.IdOption.Value != null)
                    writer.WriteString("id", validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.Id);
                else
                    writer.WriteNull("id");

            if (validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.IdentificationOption.IsSet)
                if (validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.IdentificationOption.Value != null)
                    writer.WriteString("identification", validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.Identification);
                else
                    writer.WriteNull("identification");

            if (validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.NameOption.IsSet)
                if (validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.NameOption.Value != null)
                    writer.WriteString("name", validationsApiReportingPeriodsV1PaginatedRecordsTypesReportingPeriodRecordsTypesRule.Name);
                else
                    writer.WriteNull("name");
        }
    }
}
