/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsApiReportsV1ReportPreferencesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsApiReportsV1ReportPreferencesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsApiReportsV1ReportPreferencesResponse
        //private AnalyticsApiReportsV1ReportPreferencesResponse instance;

        public AnalyticsApiReportsV1ReportPreferencesResponseTests()
        {
            // TODO uncomment below to create an instance of AnalyticsApiReportsV1ReportPreferencesResponse
            //instance = new AnalyticsApiReportsV1ReportPreferencesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsApiReportsV1ReportPreferencesResponse
        /// </summary>
        [Fact]
        public void AnalyticsApiReportsV1ReportPreferencesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsApiReportsV1ReportPreferencesResponse
            //Assert.IsType<AnalyticsApiReportsV1ReportPreferencesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'ReportId'
        /// </summary>
        [Fact]
        public void ReportIdTest()
        {
            // TODO unit test for the property 'ReportId'
        }

        /// <summary>
        /// Test the property 'Preferences'
        /// </summary>
        [Fact]
        public void PreferencesTest()
        {
            // TODO unit test for the property 'Preferences'
        }
    }
}
