/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1JobExecutionRequestedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1JobExecutionRequestedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1JobExecutionRequestedResponse
        //private DataSyncApiJobV1JobExecutionRequestedResponse instance;

        public DataSyncApiJobV1JobExecutionRequestedResponseTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1JobExecutionRequestedResponse
            //instance = new DataSyncApiJobV1JobExecutionRequestedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1JobExecutionRequestedResponse
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1JobExecutionRequestedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1JobExecutionRequestedResponse
            //Assert.IsType<DataSyncApiJobV1JobExecutionRequestedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
    }
}
