/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto
        //private EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto instance;

        public EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDtoTests()
        {
            // TODO uncomment below to create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto
            //instance = new EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto
        /// </summary>
        [Fact]
        public void EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto
            //Assert.IsType<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramCatalogEntryRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ProgramType'
        /// </summary>
        [Fact]
        public void ProgramTypeTest()
        {
            // TODO unit test for the property 'ProgramType'
        }

        /// <summary>
        /// Test the property 'EligibilityCriteria'
        /// </summary>
        [Fact]
        public void EligibilityCriteriaTest()
        {
            // TODO unit test for the property 'EligibilityCriteria'
        }

        /// <summary>
        /// Test the property 'RequiredDocuments'
        /// </summary>
        [Fact]
        public void RequiredDocumentsTest()
        {
            // TODO unit test for the property 'RequiredDocuments'
        }

        /// <summary>
        /// Test the property 'InternalDisplayName'
        /// </summary>
        [Fact]
        public void InternalDisplayNameTest()
        {
            // TODO unit test for the property 'InternalDisplayName'
        }
    }
}
