/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest
        //private EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest instance;

        public EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequestTests()
        {
            // TODO uncomment below to create an instance of EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest
            //instance = new EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest
        /// </summary>
        [Fact]
        public void EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest
            //Assert.IsType<EdGraphHttpAggregatorsTenantApiServicesObservationsUpsertObservationDraftRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Fact]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'CurrentStep'
        /// </summary>
        [Fact]
        public void CurrentStepTest()
        {
            // TODO unit test for the property 'CurrentStep'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'ObservationId'
        /// </summary>
        [Fact]
        public void ObservationIdTest()
        {
            // TODO unit test for the property 'ObservationId'
        }
    }
}
