/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EvaluationApiEvaluationsV1EvaluationStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EvaluationApiEvaluationsV1EvaluationStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EvaluationApiEvaluationsV1EvaluationStatus
        //private EvaluationApiEvaluationsV1EvaluationStatus instance;

        public EvaluationApiEvaluationsV1EvaluationStatusTests()
        {
            // TODO uncomment below to create an instance of EvaluationApiEvaluationsV1EvaluationStatus
            //instance = new EvaluationApiEvaluationsV1EvaluationStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EvaluationApiEvaluationsV1EvaluationStatus
        /// </summary>
        [Fact]
        public void EvaluationApiEvaluationsV1EvaluationStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" EvaluationApiEvaluationsV1EvaluationStatus
            //Assert.IsType<EvaluationApiEvaluationsV1EvaluationStatus>(instance);
        }
    }
}
