/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1Tenant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1TenantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1Tenant
        //private IdentityApiUserV1Tenant instance;

        public IdentityApiUserV1TenantTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1Tenant
            //instance = new IdentityApiUserV1Tenant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1Tenant
        /// </summary>
        [Fact]
        public void IdentityApiUserV1TenantInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1Tenant
            //Assert.IsType<IdentityApiUserV1Tenant>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

        /// <summary>
        /// Test the property 'EducationOrganizations'
        /// </summary>
        [Fact]
        public void EducationOrganizationsTest()
        {
            // TODO unit test for the property 'EducationOrganizations'
        }

        /// <summary>
        /// Test the property 'Licenses'
        /// </summary>
        [Fact]
        public void LicensesTest()
        {
            // TODO unit test for the property 'Licenses'
        }

        /// <summary>
        /// Test the property 'OrganizationName'
        /// </summary>
        [Fact]
        public void OrganizationNameTest()
        {
            // TODO unit test for the property 'OrganizationName'
        }
    }
}
