/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IMSAdminApiV1ConnectionsConnectionDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IMSAdminApiV1ConnectionsConnectionDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IMSAdminApiV1ConnectionsConnectionDetails
        //private IMSAdminApiV1ConnectionsConnectionDetails instance;

        public IMSAdminApiV1ConnectionsConnectionDetailsTests()
        {
            // TODO uncomment below to create an instance of IMSAdminApiV1ConnectionsConnectionDetails
            //instance = new IMSAdminApiV1ConnectionsConnectionDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IMSAdminApiV1ConnectionsConnectionDetails
        /// </summary>
        [Fact]
        public void IMSAdminApiV1ConnectionsConnectionDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" IMSAdminApiV1ConnectionsConnectionDetails
            //Assert.IsType<IMSAdminApiV1ConnectionsConnectionDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
