/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SettingsApiUserSettingsV1SearchUserSettingsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettingsApiUserSettingsV1SearchUserSettingsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SettingsApiUserSettingsV1SearchUserSettingsResponse
        //private SettingsApiUserSettingsV1SearchUserSettingsResponse instance;

        public SettingsApiUserSettingsV1SearchUserSettingsResponseTests()
        {
            // TODO uncomment below to create an instance of SettingsApiUserSettingsV1SearchUserSettingsResponse
            //instance = new SettingsApiUserSettingsV1SearchUserSettingsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettingsApiUserSettingsV1SearchUserSettingsResponse
        /// </summary>
        [Fact]
        public void SettingsApiUserSettingsV1SearchUserSettingsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SettingsApiUserSettingsV1SearchUserSettingsResponse
            //Assert.IsType<SettingsApiUserSettingsV1SearchUserSettingsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
