// <auto-generated>
/*
 * Tenant Api
 *
 * Tenant Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdGraph.Platform.Client.Client;

namespace EdGraph.Platform.Client.Model
{
    /// <summary>
    /// Defines DataSyncApi.JobExecution.V1.JobExecutionStatus
    /// </summary>
    public enum DataSyncApiJobExecutionV1JobExecutionStatus
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        Unknown,

        /// <summary>
        /// Enum Queued for value: Queued
        /// </summary>
        Queued,

        /// <summary>
        /// Enum Running for value: Running
        /// </summary>
        Running,

        /// <summary>
        /// Enum Completed for value: Completed
        /// </summary>
        Completed,

        /// <summary>
        /// Enum CompletedWithErrors for value: CompletedWithErrors
        /// </summary>
        CompletedWithErrors,

        /// <summary>
        /// Enum Cancelled for value: Cancelled
        /// </summary>
        Cancelled,

        /// <summary>
        /// Enum Error for value: Error
        /// </summary>
        Error
    }

    /// <summary>
    /// Converts <see cref="DataSyncApiJobExecutionV1JobExecutionStatus"/> to and from the JSON value
    /// </summary>
    public static class DataSyncApiJobExecutionV1JobExecutionStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="DataSyncApiJobExecutionV1JobExecutionStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DataSyncApiJobExecutionV1JobExecutionStatus FromString(string value)
        {
            if (value.Equals("Unknown"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Unknown;

            if (value.Equals("Queued"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Queued;

            if (value.Equals("Running"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Running;

            if (value.Equals("Completed"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Completed;

            if (value.Equals("CompletedWithErrors"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.CompletedWithErrors;

            if (value.Equals("Cancelled"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Cancelled;

            if (value.Equals("Error"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Error;

            throw new NotImplementedException($"Could not convert value to type DataSyncApiJobExecutionV1JobExecutionStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="DataSyncApiJobExecutionV1JobExecutionStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DataSyncApiJobExecutionV1JobExecutionStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("Unknown"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Unknown;

            if (value.Equals("Queued"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Queued;

            if (value.Equals("Running"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Running;

            if (value.Equals("Completed"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Completed;

            if (value.Equals("CompletedWithErrors"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.CompletedWithErrors;

            if (value.Equals("Cancelled"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Cancelled;

            if (value.Equals("Error"))
                return DataSyncApiJobExecutionV1JobExecutionStatus.Error;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="DataSyncApiJobExecutionV1JobExecutionStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(DataSyncApiJobExecutionV1JobExecutionStatus value)
        {
            if (value == DataSyncApiJobExecutionV1JobExecutionStatus.Unknown)
                return "Unknown";

            if (value == DataSyncApiJobExecutionV1JobExecutionStatus.Queued)
                return "Queued";

            if (value == DataSyncApiJobExecutionV1JobExecutionStatus.Running)
                return "Running";

            if (value == DataSyncApiJobExecutionV1JobExecutionStatus.Completed)
                return "Completed";

            if (value == DataSyncApiJobExecutionV1JobExecutionStatus.CompletedWithErrors)
                return "CompletedWithErrors";

            if (value == DataSyncApiJobExecutionV1JobExecutionStatus.Cancelled)
                return "Cancelled";

            if (value == DataSyncApiJobExecutionV1JobExecutionStatus.Error)
                return "Error";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DataSyncApiJobExecutionV1JobExecutionStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class DataSyncApiJobExecutionV1JobExecutionStatusJsonConverter : JsonConverter<DataSyncApiJobExecutionV1JobExecutionStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override DataSyncApiJobExecutionV1JobExecutionStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            DataSyncApiJobExecutionV1JobExecutionStatus? result = rawValue == null
                ? null
                : DataSyncApiJobExecutionV1JobExecutionStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DataSyncApiJobExecutionV1JobExecutionStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataSyncApiJobExecutionV1JobExecutionStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, DataSyncApiJobExecutionV1JobExecutionStatus dataSyncApiJobExecutionV1JobExecutionStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(dataSyncApiJobExecutionV1JobExecutionStatus.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DataSyncApiJobExecutionV1JobExecutionStatus"/>
    /// </summary>
    public class DataSyncApiJobExecutionV1JobExecutionStatusNullableJsonConverter : JsonConverter<DataSyncApiJobExecutionV1JobExecutionStatus?>
    {
        /// <summary>
        /// Returns a DataSyncApiJobExecutionV1JobExecutionStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override DataSyncApiJobExecutionV1JobExecutionStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            DataSyncApiJobExecutionV1JobExecutionStatus? result = rawValue == null
                ? null
                : DataSyncApiJobExecutionV1JobExecutionStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataSyncApiJobExecutionV1JobExecutionStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, DataSyncApiJobExecutionV1JobExecutionStatus? dataSyncApiJobExecutionV1JobExecutionStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(dataSyncApiJobExecutionV1JobExecutionStatus?.ToString() ?? "null");
        }
    }
}
