/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1SEOAAUpdatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1SEOAAUpdatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1SEOAAUpdatedResponse
        //private IdentityApiUserV1SEOAAUpdatedResponse instance;

        public IdentityApiUserV1SEOAAUpdatedResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1SEOAAUpdatedResponse
            //instance = new IdentityApiUserV1SEOAAUpdatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1SEOAAUpdatedResponse
        /// </summary>
        [Fact]
        public void IdentityApiUserV1SEOAAUpdatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1SEOAAUpdatedResponse
            //Assert.IsType<IdentityApiUserV1SEOAAUpdatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'SeoaaId'
        /// </summary>
        [Fact]
        public void SeoaaIdTest()
        {
            // TODO unit test for the property 'SeoaaId'
        }
    }
}
