/*
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1SectionAddedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1SectionAddedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1SectionAddedResponse
        //private IdentityApiUserV1SectionAddedResponse instance;

        public IdentityApiUserV1SectionAddedResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1SectionAddedResponse
            //instance = new IdentityApiUserV1SectionAddedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1SectionAddedResponse
        /// </summary>
        [Fact]
        public void IdentityApiUserV1SectionAddedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1SectionAddedResponse
            //Assert.IsType<IdentityApiUserV1SectionAddedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'EducationOrganizationId'
        /// </summary>
        [Fact]
        public void EducationOrganizationIdTest()
        {
            // TODO unit test for the property 'EducationOrganizationId'
        }

        /// <summary>
        /// Test the property 'UserSectionId'
        /// </summary>
        [Fact]
        public void UserSectionIdTest()
        {
            // TODO unit test for the property 'UserSectionId'
        }
    }
}
