/*
 * Validations Api
 *
 * Validations Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Platform.Client.Model;
using EdGraph.Platform.Client.Client;
using System.Reflection;

namespace EdGraph.Platform.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ValidationsApiTagsV1TagDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidationsApiTagsV1TagDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidationsApiTagsV1TagDto
        //private ValidationsApiTagsV1TagDto instance;

        public ValidationsApiTagsV1TagDtoTests()
        {
            // TODO uncomment below to create an instance of ValidationsApiTagsV1TagDto
            //instance = new ValidationsApiTagsV1TagDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidationsApiTagsV1TagDto
        /// </summary>
        [Fact]
        public void ValidationsApiTagsV1TagDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidationsApiTagsV1TagDto
            //Assert.IsType<ValidationsApiTagsV1TagDto>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Fact]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }
    }
}
